// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV8cheaOUlZAUmej6FPYXybM-y1nZV7iA',
    appId: '1:297825207215:web:5bef91160db540921ae55a',
    messagingSenderId: '297825207215',
    projectId: 'everafter-36b32',
    authDomain: 'everafter-36b32.firebaseapp.com',
    storageBucket: 'everafter-36b32.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrJEGoPq05dLywdwCdVqGSEfNih82maXo',
    appId: '1:297825207215:android:6950303dfc5f6e0e1ae55a',
    messagingSenderId: '297825207215',
    projectId: 'everafter-36b32',
    storageBucket: 'everafter-36b32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpxJHhbo1waHntD75FogTY4xuphyDgk98',
    appId: '1:297825207215:ios:ef417f6195a021631ae55a',
    messagingSenderId: '297825207215',
    projectId: 'everafter-36b32',
    storageBucket: 'everafter-36b32.appspot.com',
    iosBundleId: 'com.example.remindMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpxJHhbo1waHntD75FogTY4xuphyDgk98',
    appId: '1:297825207215:ios:d289526f1cc9e2a71ae55a',
    messagingSenderId: '297825207215',
    projectId: 'everafter-36b32',
    storageBucket: 'everafter-36b32.appspot.com',
    iosBundleId: 'com.example.remindMe.RunnerTests',
  );
}
