const interests = [
  "hiking",
  "cooking",
  "cycling",
  "sky diving",
  "night life",
  "traveling",
  "outdoor activities",
  "writing",
  "arts & crafts",
  "photography",
  "Gardening & plants",
  "reading",
  "gambling",
  "mobile gaming",
  "partying",
  "dancing",
  "sports",
  "foodie",
  "visiting new places",
  "movie dates",
  "swimming",
  "painting",
  "karaoke",
  "computer games",
  "board games",
  "paint balling",
  "driving"
  "clubbing",
  "archery",
  "tennis",
  "football",
  "basketball",
  "chess",
  "gisting",
  "texting",
  "making music",
  "making videos",
  "pets & walks",
  "concerts",
];